In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# constants
num_inputs = 2
num_neurons = 3

In [3]:
# placeholders
x0 = tf.placeholder(tf.float32, [None, num_inputs])
x1 = tf.placeholder(tf.float32, [None, num_inputs])

In [4]:
#variables
Wx = tf.Variable(tf.random_normal(shape=[num_inputs, num_neurons]))
Wy = tf.Variable(tf.random_normal(shape=[num_neurons,num_neurons]))
b = tf.Variable(tf.zeros(shape=[1,num_neurons]))

y0 = tf.tanh(tf.matmul(x0,Wx) + b)
y1 = tf.tanh(tf.matmul(y0,Wy) + tf.matmul(x1,Wx) + b)

In [5]:
X0 = np.array([[0,1],[2,3],[4,5]])
X1 = np.array([[100,101],[102,103],[104,105]])

In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    y0_op, y1_op = sess.run([y0, y1], feed_dict={x0:X0, x1:X1})
    print(y0_op)
    print(y1_op)

[[-0.09513842  0.57513535  0.63348013]
 [-0.86103773  0.7518785  -0.60948229]
 [-0.98659468  0.86155897 -0.97392493]]
[[-1.  1. -1.]
 [-1.  1. -1.]
 [-1.  1. -1.]]
