In [1]:
import tensorflow as tf
import numpy as np

/home/sujit25/anaconda3/envs/ml_env/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
n_features = 10
n_dense_neurons = 3

In [9]:
# define graph
x = tf.placeholder(dtype=tf.float32, shape=(None, n_features))
w = tf.Variable(dtype=tf.float32, initial_value= tf.random_normal(shape=(n_features, n_dense_neurons), mean=0, stddev=1))
b = tf.Variable(dtype=tf.float32, initial_value= tf.zeros(shape=(n_dense_neurons)))

# linear mapping 
xW = tf.matmul(x, w)
z = tf.add(xW, b)
a = tf.sigmoid(z)

In [10]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    
    computed_a = sess.run(a, feed_dict={x: np.random.uniform(low=0, high=1, size=(10, n_features))})
    print(computed_a)

[[0.6714236  0.7740478  0.19616568]
 [0.6897649  0.46106768 0.33339578]
 [0.5029633  0.8992419  0.00901688]
 [0.4273301  0.7151545  0.06284306]
 [0.47875416 0.7145208  0.02497862]
 [0.6183666  0.6272834  0.23861265]
 [0.40670803 0.7936248  0.32591733]
 [0.2929316  0.74657196 0.12238894]
 [0.45268714 0.21656454 0.09361807]
 [0.2803398  0.5034608  0.16987415]]
