In [1]:
import tensorflow as tf

/home/sujit25/anaconda3/envs/ml_env/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.7.0


In [4]:
hello = tf.constant("Hello")
world = tf.constant("World")

In [5]:
with tf.Session() as sess:
    print(sess.run(hello + world))

b'HelloWorld'


In [7]:
a = tf.constant(10)
b= tf.constant(20)
c= a + b

with tf.Session() as sess:
    print(sess.run(c))

30


In [9]:
const_val = tf.constant(10)
fill_mat = tf.fill((4,4),const_val)
zeros_mat = tf.zeros((4,4))
ones_mat = tf.ones((4,4))
random_mat = tf.random_normal(shape=(4,4), mean=0.0, stddev = 1.0, dtype=tf.float32)

with tf.Session() as sess:
    print("filled mat", sess.run(fill_mat))
    print("zeros mat", sess.run(zeros_mat))
    print("ones mat", sess.run(ones_mat))
    print("random mat", sess.run(random_mat))
    

filled mat [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
zeros mat [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones mat [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
random mat [[ 0.44483092  0.92475903 -0.90111125  1.581093  ]
 [ 0.9971793   0.60088885 -0.55525357  0.39798424]
 [ 0.63436127  0.19315493  0.07892652 -0.2571966 ]
 [ 0.6058792  -0.24564922 -0.28464445  0.4849493 ]]


In [11]:
shape_op = tf.shape(fill_mat)
with tf.Session() as sess:
    print(sess.run(shape_op))

[4 4]
